email:
  max_length: 150
password:
  min_length: 6
  max_length: 16
name:
  max_length: 50
  min_length: 2
language_image: "https://res.cloudinary.com/tdh/image/upload/v1595343877/images/language_uyra3n.png"
logo_image: "logo2.png"
carosel_image: "elearning-way-improve-employee-engagement.jpg"
per: 5
default_start_date: "01/01/1900"
date_format: "%Y/%m/%d"
user_course_per: 10
default_page: 1
min_age: 12
max_age: 100
description:
  max_length: 250
favicon_logo: "logo2.png"
trophy_img: "trophy.png"
status:
  active: "active"
  finish: "finish"
  pending: "pending"
relationship:
  student: "student"
  active: "active"
  pending: "pending"
limit_newest_cate: 7
limit_course_suggest: 7
default_id: 1
